### PR TITLE
Merge with betterWhiteSpace

### PR DESCRIPTION
**Pull request by chmln**
As discussed in https://github.com/spywhere/vscode-whiteviz/pull/1
:tada:

### CODE REVIEW

**Comment by spywhere** [comment]
I'll take a look tonight and will merged upon reviewed.

**Comment by spywhere** [comment]
The extension has been published (v0.3.0). I also improve your decoration setup to make the continuous line of tab indicator and size consistency.

screen shot 2560-05-25 at 10 28 07

**Comment by chmln** [comment]
Awesome!

But..the whole reason I made my separate extension was to get rid of the hideous tab indicator, which is still the default in `whiteviz`.

I think its best *not* to have it configurable and make the best choice for the user, providing em-dash tabs out-of-the-box. There should be better defaults and less options to choose from, since most users won't be customizing them.

Also, the tab character has to be determined dynamically based on user's `tabSize` editor option, since you need a different char for two-width and four-width tabs.

**Comment by spywhere** [comment]
The reasons why I want the extension to be customizable is because of it is not just whitespace visualization (upon selection) that I want this extension to cover, but many issues (such as https://github.com/microsoft/vscode/issues/2085 or https://github.com/microsoft/vscode/issues/2878) can also be covered. With this, they can make the best out of one extension instead of choosing multiple variations just to suit them.

Yes, most user might not customizing it, but provide it as a customizable option help power users to specifically choose which feature they want to enabled.

And since some users might not from a modern text editor, set the default options to something else that seems not align with the editor's look and feel, it would give the editor a bit strange to those users, as you state that most users would not customizing them.

For `tabSize`, although Unicode provided those tab variations as you are currently using, the actual size when using it in the editor is different, so that is why I use the full-width em-dash instead. Though you could said that setting it to some specific font would give the same effect, however, not every machine have the same font set and not to mention if the users change their editor's font.

Hopefully you would understand the points behind the decision I am making here.

Anyway, thanks for the comment.

**Pull request merged**
